[package]
name = "compressedheaders"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]

[dependencies]
serde = "1.0.2"
serde_json = "1.0.1"
serde_derive = "1.0.2"
hyper = "0.11.6"
rust-crypto = "0.2"
futures = "0.1.14"
tokio-core = "0.1.8"
