[package]
name = "rust-bitcoin-headers"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]

[dependencies]
bitcoin = "0.9.0"
serde = "1.0.2"
serde_json = "1.0.1"
serde_derive = "1.0.2"
hyper = "0.10"
rust-crypto = "0.2"